CodeAlongGr9/Controllers/CarsController.cs
using CodeAlongGr9.Data;
using Microsoft.AspNetCore.Mvc;

namespace CodeAlongGr9.Controllers
{
    public class CarsController : Controller
    {

        readonly ApplicationDbContext _context;

        public CarsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Cars.ToList());
        }
    }
}

CodeAlongGr9/Controllers/CheckController.cs
using CodeAlongGr9.Models;
using Microsoft.AspNetCore.Mvc;

namespace CodeAlongGr9.Controllers
{
    public class CheckController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        //GET
        public IActionResult CheckAge()
        {
            return View(); 
        }
        [HttpPost]
        public IActionResult CheckAge(int age)
        {
            ViewBag.Message = CheckModel.CheckAge(age);
            return View();
        }

        public IActionResult SetSession()
        {
            return View(); 
        }

        [HttpPost]
        public IActionResult SetSession(string input)
        {
            if (input != null)
            {
                CookieOptions cookieOptions = new CookieOptions();
                cookieOptions.Expires = DateTime.Now.AddMinutes(5);

                HttpContext.Session.SetString("session", input);
                HttpContext.Response.Cookies.Append("cookie", input, cookieOptions);
                ViewBag.Message = "Session has been set!";
            }
            //else
            //    ViewBag.Message = "Nothing was saved to the session!";

            return View(); 
        }

        public IActionResult GetSession()
        {
            ViewBag.SessionMessage = HttpContext.Session.GetString("session");
            ViewBag.CookieMessage = HttpContext.Request.Cookies["cookie"];
            return View();
        }

    }
}

CodeAlongGr9/Controllers/PeopleController.cs
using CodeAlongGr9.Data;
using CodeAlongGr9.Models;
using Microsoft.AspNetCore.Mvc;

namespace CodeAlongGr9.Controllers
{
    public class PeopleController : Controller
    {
        readonly ApplicationDbContext _context;

        public PeopleController(ApplicationDbContext context)
        {
            _context = context;
        }

         public IActionResult Index()
        {
            List<Person> listOfPeople = _context.People.ToList();
            
            return View(listOfPeople);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Person person)
        {
            if(ModelState.IsValid)
            {
                _context.People.Add(person);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public IActionResult Edit(string ssn)
        {
            var person = _context.People.FirstOrDefault(x => x.SSN == ssn);
            return View(person);
        }
        [HttpPost]
        public IActionResult Edit(Person person)
        {
            _context.Update(person);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Delete(string ssn)
        {
            var person = _context.People.FirstOrDefault(x => x.SSN == ssn);

            _context.People.Remove(person);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

CodeAlongGr9/Controllers/RoleController.cs
using CodeAlongGr9.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CodeAlongGr9.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RoleController : Controller
    {
        readonly RoleManager<IdentityRole> _roleManager;
        readonly UserManager<ApplicationUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View(_roleManager.Roles);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create (IdentityRole role)
        {
            role.NormalizedName = role.Name.ToUpper();
            await _roleManager.CreateAsync(role);

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            await _roleManager.DeleteAsync(role);
            return RedirectToAction("Index");
        }

        public IActionResult AddUserToRole()
        {
            ViewBag.Users = new SelectList(_userManager.Users, "Id", "UserName");
            ViewBag.Roles = new SelectList(_roleManager.Roles, "Name", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddUserToRole(string userId, string roleName)
        {
            var user = await _userManager.FindByIdAsync(userId);
            await _userManager.AddToRoleAsync(user, roleName);

            return RedirectToAction("Index");
        }

        public IActionResult ShowAllUsers()
        {
            return View(_userManager.Users);
        }

        public async Task<IActionResult> ShowUserRoles(string Id)
        {
            UserRoleViewModel vm = new UserRoleViewModel();
            var user = await _userManager.FindByIdAsync(Id);

            var assignedRoles = new List<string>(await _userManager.GetRolesAsync(user));
            vm.UserId = Id;
            vm.UserName = user.UserName;

            vm.Roles.AddRange(assignedRoles);

            return View(vm);
        }
        public async Task<IActionResult> RemoveRoleFromUser(string rolename, string userid)
        {
            var user = await _userManager.FindByIdAsync(userid);
            await _userManager.RemoveFromRoleAsync(user, rolename);
            return RedirectToAction("ShowUserRoles", new { id = userid });
        }

    }
}

CodeAlongGr9/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CodeAlong Grupp 9</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Test">Test</a>
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Test for action link","Test","Home")
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Check" asp-action="CheckAge">Check age</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Check" asp-action="SetSession">Set session</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="People" asp-action="Index">People</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cars" asp-action="Index">Cars</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="CarOwner" asp-action="AddOwnerToCar">Add owner to car</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Role" asp-action="Index">Check roles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Role" asp-action="ShowAllUsers">Check users</a>
                            </li>
                        }


                        <li class="nav-item">
                            <partial name="_LoginPartial" />
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        @RenderBody()
    </div>
    @await RenderSectionAsync("Scripts", required:false)
</body>
<footer class="container">&copy;@DateTime.Now.Year</footer>
</html>